// Generated by scripts/build-bert-vocab.mjs -- do not edit by hand.
//
// A content hash of static/bert-vocab-zh.txt, and the model it belongs to. Both are part of
// the tagger's version, so changing either restamps every document and re-derives it.
export const BERT_VOCAB_VERSION = '8550a78c';
export const BERT_MODEL = 'Xenova/bert-base-chinese-ws';
export const BERT_VOCAB_ENTRIES = 21128;
