// Generated by scripts/build-wordlist.mjs -- do not edit by hand.
//
// A content hash of static/wordlist-zh.txt. It is part of the analyzer's version so that
// regenerating the word list restamps every document and re-derives it, rather than leaving
// two different segmentations sharing one version (ADR-0011).
export const WORDLIST_VERSION = 'd94bc1a4';
export const WORDLIST_WORDS = 120176;
